image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - rm -rf node_modules/ build/
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - build/
  only:
    - master

production:
  type: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=narutoquest --api-key='5ce5511a-538d-49f9-9f9a-5302b99d36af'
  only:
    - master
