language: node_js
node_js:
  - '12.0.0'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - rm -rf node_modules/ build/
  - yarn install
  - yarn build

deploy:
  provider: heroku
  api_key:
    secure: 24649adc-7259-402c-b971-23dfc0b92e8c
  app: narutoquest
  on:
    branch: master
